title: John Doe # your name (or website title) here
logo: "/images/italo_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, welcome to my github, here you can find some of the projects i've been working  
  Skills:
  * Programming: 
    * C++ for microcontrollers
      *PIC, ATMEL, Expressif, Raspberry
    * Python
      * OpenCV
      * RPA, PyAutoGui
      * ArcGIS / PowerBI
  * 3D Modelling:
    * Solidworks
    * Fusion 360
    * Materialize Magics
  <a href="https://www.linkedin.com/in/italocjs/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
